"""The `/短劇` screenwriter: one story premise -> a validated `Screenplay`.

Pure, like `prompts.convert`: takes an `LlmClient`, does no I/O of its own,
and everything the model returns goes through pydantic before it can spend a
GPU-second. Three calls rather than one, because the pod's inference server
caps a json-only reply at `MAX_NEW_TOKENS_CEILING` (1536 tokens) and six full
shots plus a character sheet do not reliably fit:

1. **outline** -- title, logline, style, the `CharacterAnchor`, the
   `WorldBible`, six named beats (hook / setup / conflict / turn / payoff /
   cliffhanger).
2. **shots 1-3** and 3. **shots 4-6** -- each beat expanded into its
   template slot: one or two sub-shots, each a framing, an action, a camera
   move and at most one spoken line. The second call is told how the third
   shot ended so the framing alternation holds across the seam.

**No template fallback.** `prompts.convert` degrades to a one-line template
because a mediocre clip beats a dropped request. A drama is different: a
"template" would be six clips of nothing in particular, at six times the
cost. `write_screenplay` raises `ScreenplayError` and the job fails loudly.

**The model writes what only it can; code composes the rest.** The model
writes the scene, the actions, the framings and the lines. Code owns the
durations and cut points (the beat template), the keyframe prompt (anchor +
world bible first, verbatim), the speaker identity, and the H3 prompt -- so
the verbatim-anchor rule `core.drama_spec.Screenplay` enforces is met by
construction. The model writes the story; it does not get to write the face.
"""

from __future__ import annotations

import json
from typing import Any, Protocol

from ai_studio.core.enums import TransitionReason
from ai_studio.prompts.convert import camera_from_spec, extract_json
from ai_studio.prompts.flux import QUALITY_SUFFIX
from ai_studio.prompts.h3 import Dialogue, H3Mode, H3Prompt, PromptShot
from pydantic import ValidationError

from fun_workflow.core.drama_spec import (
    BEAT_TEMPLATE,
    SHOT_COUNT,
    BeatSlot,
    CharacterAnchor,
    DramaLine,
    DramaShot,
    Framing,
    Screenplay,
    SubShot,
    WorldBible,
)


class LlmClient(Protocol):
    async def complete(self, system: str, user: str, *, max_tokens: int = 1200) -> str: ...


class ScreenplayError(Exception):
    """The screenwriter could not produce a valid screenplay. Terminal."""


OUTLINE_MAX_TOKENS = 1100
SHOTS_MAX_TOKENS = 1400
"""Under the inference server's 1536 ceiling with room for the harmony
channel markers. Both `[speculative]` until a real token count is measured."""

MAX_LINE_CHARS = 15
"""One caption line. Longer lines break in two on screen and take longer
than a sub-shot gives the viewer to read them."""

_FRAMINGS = " | ".join(f.value for f in Framing)
_CAMERA_MOTIONS = (
    "zoom_in zoom_out push_in pull_out pan_left pan_right truck_left truck_right "
    "tilt_up tilt_down pedestal_up pedestal_down arc_shot tracking_shot static_shot "
    "shake_slightly pov"
)

OUTLINE_SYSTEM = """\
You are a screenwriter for one-minute short dramas generated by a video model.
Reply with JSON only, no prose and no code fence.

Schema:
{
  "title": "<short title, may be Chinese>",
  "logline": "<one sentence: who wants what, what stands in the way>",
  "style": "<visual style, e.g. 'Live-action, cinematic' or '2D-animated'>",
  "anchor": {
    "name": "<the lead's name>",
    "appearance": "<English. 12-30 words of CONCRETE, STABLE facial and hair \
features: age, ethnicity, face shape, one distinguishing mark, hair colour, \
length and style. Example: '25-year-old Asian woman, oval face, small mole under \
right eye, dark chin-length straight hair'. No mood words, no beauty words.>",
    "wardrobe": "<English. What the lead wears for the whole drama.>",
    "voice": "<English. How the lead sounds, e.g. 'soft, low, slightly hoarse'.>"
  },
  "world": {
    "location": "<English. The one setting and its layout, e.g. 'a narrow \
night-market stall facing a single row of neighbouring stalls'>",
    "light": "<English. Light direction and colour, e.g. 'warm tungsten string \
lights from above left'>",
    "signature_prop": "<English. One object visible in every shot, e.g. 'a \
folded paper letter'>"
  },
  "beats": {
    "hook": "<a concrete, visible oddity the viewer sees in the first 2 seconds>",
    "setup": "<who the lead is and what they want, shown not told>",
    "conflict": "<what stands in the way, in one action>",
    "turn": "<the reversal: something the lead believed is shown false>",
    "payoff": "<what the lead does about it>",
    "cliffhanger": "<an unresolved end state, an open question, not a moral>"
  },
  "overall_soundscape": "<1-3 English sentences: ambience and action sounds shared \
by the whole drama>",
  "non_diegetic_music": "<1-2 English sentences on instrumentation, tempo and \
dynamics, or exactly N/A>"
}

Rules:
- Every beat is one English sentence that changes something: a state before,
  an event, a state after. One lead character throughout; other people may
  appear but stay unnamed and in the background.
- One location for the whole drama. The premise is the spec: keep every
  concrete thing the user named (places, objects, names, moods) and invent
  only what is needed to fill six beats.
- appearance/wardrobe/voice are English and concrete. Never describe the face
  anywhere else than in "appearance".
"""

SHOTS_SYSTEM = f"""\
You expand story beats into shots for the MiniMax H3 video model. Each shot is
one clip rendered from a still first frame; a shot with two sub-shots is one
clip in which the model itself cuts to the second framing at the given time.
Reply with JSON only, no prose and no code fence.

Schema:
{{
  "shots": [
    {{
      "index": <the shot number given>,
      "scene": "<English. What is around the lead in this shot: props, weather, \
time of day. Concrete and visible. Do NOT describe the lead's face or hair, \
and do not repeat the location or the light -- they are pasted in.>",
      "cut_reason": "<default|time_passing|topic_change|drill_down: what the cut \
INTO this shot means>",
      "sub_shots": [
        {{
          "framing": "<one of: {_FRAMINGS}>",
          "action": "<English. The ONE visible thing the lead does, ending in a \
pose that can hold still. Say 'the lead', never a face word.>",
          "camera": {{
            "motion": "<one of: {_CAMERA_MOTIONS}>",
            "amplitude": "<small|medium|large>",
            "speed": "<slow|normal|fast>",
            "toward": "<optional: what the camera moves toward>"
          }},
          "line": "<optional: the lead's spoken words, in the premise's language, \
at most {MAX_LINE_CHARS} characters>",
          "narration": "<required when there is no line: a short caption in the \
premise's language, at most {MAX_LINE_CHARS} characters, stating what the \
picture can't guarantee -- a reason, a relationship, a time skip. Not a \
description of the visible action; the picture already shows that.>"
        }}
      ]
    }}
  ]
}}

Rules:
- One shot per beat, in the order given, with the given index and exactly the
  number of sub-shots given.
- Framing ALTERNATES: no two consecutive sub-shots share a framing, counting
  across shots and across the previous shot's last framing when one is given.
  Vary between wide, medium and close so the lead is re-established each cut.
- The camera motion push_in is reserved for the turn shot, once. Everywhere
  else use static_shot, a slow pan, a tilt or a tracking shot.
- Every sub-shot has exactly one of "line" or "narration", never both, never
  neither. Use "line" only when the beat implies speech, at most one per
  sub-shot, at most {MAX_LINE_CHARS} characters. Otherwise write "narration":
  the one sentence a viewer needs to follow the story that the picture alone
  cannot guarantee, not a restatement of "action".
- The lead is on screen in every sub-shot, doing the action. A prop alone
  (a phone buzzing, a door opening) is not a shot: the lead reacts to it.
- Never mention the lead's face, hair, age or ethnicity: the appearance is
  supplied separately and pasted in verbatim. Refer to "the lead".
- Everything is English except "line"/"narration", which stay in the
  premise's language.
"""

_CUT_REASONS = {r.value: r for r in TransitionReason}
_FRAMING_BY_VALUE = {f.value: f for f in Framing}


# ------------------------------------------------------------------------ builders


def build_outline(payload: dict[str, Any]) -> dict[str, Any]:
    """Validate the outline reply into its typed parts. Raises `ScreenplayError`."""
    beats = payload.get("beats")
    if isinstance(beats, list):  # tolerate the older list shape, in template order
        beats = {slot.beat.value: b for slot, b in zip(BEAT_TEMPLATE, beats, strict=False)}
    if not isinstance(beats, dict):
        raise ScreenplayError(f"outline needs a beats object, got {beats!r}")
    ordered: list[str] = []
    for slot in BEAT_TEMPLATE:
        text = beats.get(slot.beat.value)
        if not isinstance(text, str) or not text.strip():
            raise ScreenplayError(f"outline needs exactly {SHOT_COUNT} beats; '{slot.beat.value}' is missing")
        ordered.append(text.strip())
    try:
        anchor = CharacterAnchor.model_validate(payload.get("anchor") or {})
        world = WorldBible.model_validate(payload.get("world") or {})
    except ValidationError as exc:
        raise ScreenplayError(f"invalid anchor or world: {exc}") from exc
    title = str(payload.get("title") or "").strip()
    logline = str(payload.get("logline") or "").strip()
    if not title or not logline:
        raise ScreenplayError("outline needs a title and a logline")
    return {
        "title": title,
        "logline": logline,
        "style": str(payload.get("style") or "Live-action, cinematic").strip(),
        "anchor": anchor,
        "world": world,
        "beats": ordered,
        "overall_soundscape": str(payload.get("overall_soundscape") or "").strip()
        or "Quiet ambient room tone with the lead's own movement audible over it.",
        "non_diegetic_music": str(payload.get("non_diegetic_music") or "N/A").strip(),
    }


def _line(spec: Any, anchor: CharacterAnchor) -> tuple[DramaLine, ...]:
    """The model writes only the words; speaker and voice are ours."""
    text = spec if isinstance(spec, str) else (spec or {}).get("text") if isinstance(spec, dict) else None
    if not isinstance(text, str) or not text.strip():
        return ()
    identity = f"{anchor.name}, {anchor.voice}" if anchor.voice else anchor.name
    return (DramaLine(speaker_id="S1", identity=identity, text=text.strip()),)


def _sub_shot(index: int, spec: Any, *, shot: int, anchor: CharacterAnchor) -> SubShot:
    if not isinstance(spec, dict):
        raise ScreenplayError(f"shot {shot} sub-shot {index} was not an object")
    framing_text = str(spec.get("framing") or "").strip().lower()
    framing = _FRAMING_BY_VALUE.get(framing_text)
    if framing is None:
        raise ScreenplayError(f"shot {shot} sub-shot {index}: unknown framing {framing_text!r} (valid: {_FRAMINGS})")
    action = str(spec.get("action") or "").strip()
    if not action:
        raise ScreenplayError(f"shot {shot} sub-shot {index} needs an action")
    line = spec.get("line")
    if line is None and spec.get("dialogue"):  # the older per-shot shape
        first = spec["dialogue"][0] if isinstance(spec["dialogue"], list) and spec["dialogue"] else None
        line = first.get("text") if isinstance(first, dict) else None
    narration = spec.get("narration")
    narration = narration.strip() if isinstance(narration, str) and narration.strip() else None
    try:
        return SubShot(
            index=index, framing=framing, action=action,
            camera=camera_from_spec(spec.get("camera")), dialogue=_line(line, anchor),
            narration=narration,
        )
    except ValidationError as exc:
        raise ScreenplayError(f"shot {shot} sub-shot {index} failed validation: {exc}") from exc


def build_shots(
    payload: dict[str, Any], *, expected: list[int], anchor: CharacterAnchor, world: WorldBible
) -> list[DramaShot]:
    """Validate one shots reply for the given shot indices. Raises `ScreenplayError`."""
    raw = payload.get("shots")
    if not isinstance(raw, list) or len(raw) != len(expected):
        raise ScreenplayError(f"expected shots {expected}, got {len(raw) if isinstance(raw, list) else raw!r}")
    shots: list[DramaShot] = []
    for index, spec in zip(expected, raw, strict=True):
        if not isinstance(spec, dict):
            raise ScreenplayError(f"shot {index} was not an object")
        slot = BEAT_TEMPLATE[index - 1]
        scene = str(spec.get("scene") or "").strip()
        if not scene:
            raise ScreenplayError(f"shot {index} needs a scene")
        subs_raw = spec.get("sub_shots")
        if subs_raw is None and spec.get("framing"):  # the older one-framing shape
            subs_raw = [spec]
        if not isinstance(subs_raw, list) or len(subs_raw) != slot.sub_shots:
            got = len(subs_raw) if isinstance(subs_raw, list) else subs_raw
            raise ScreenplayError(f"shot {index} ({slot.beat.value}) needs {slot.sub_shots} sub-shot(s), got {got!r}")
        subs = tuple(_sub_shot(i, s, shot=index, anchor=anchor) for i, s in enumerate(subs_raw, start=1))
        try:
            shots.append(
                DramaShot(
                    index=index,
                    beat=slot.beat,
                    frames=slot.frames,
                    scene=scene,
                    sub_shots=subs,
                    keyframe_prompt=keyframe_prompt(anchor, world, framing=subs[0].framing, scene=scene),
                    cut_reason=_CUT_REASONS.get(str(spec.get("cut_reason") or "default"), TransitionReason.DEFAULT),
                )
            )
        except ValidationError as exc:
            raise ScreenplayError(f"shot {index} failed validation: {exc}") from exc
    return shots


def keyframe_prompt(anchor: CharacterAnchor, world: WorldBible, *, framing: Framing, scene: str) -> str:
    """The Flux prompt for a shot's still first frame.

    Anchor first and verbatim, then wardrobe, the world bible verbatim, the
    first sub-shot's framing, the scene, then the same quality tail `/圖片`
    uses. Composed here so no model output can drop any of it.
    """
    return (
        f"{anchor.appearance}, wearing {anchor.wardrobe}, {world.prefix()}, "
        f"{framing.value} shot, {scene.rstrip('.')}, {QUALITY_SUFFIX}"
    )


def character_sheet_prompts(anchor: CharacterAnchor, world: WorldBible) -> dict[str, str]:
    """The two reference stills every keyframe is repainted from.

    Shot *in the world*, not in a grey studio: image-to-image keeps a lot of
    the source's backdrop at any denoise a face survives, and 📏 2026-08-29
    the first real drama's wide keyframes came out on the sheet's plain grey
    wall with no store in sight. A sheet that already stands where the story
    happens gives every keyframe the right room to start from.
    """
    base = f"{anchor.appearance}, wearing {anchor.wardrobe}, {world.prefix()}"
    return {
        "front": (
            f"{base}, front-facing head-and-shoulders portrait, neutral expression, "
            f"soft even lighting on the face, {QUALITY_SUFFIX}"
        ),
        "three_quarter": (
            f"{base}, three-quarter view portrait turned slightly left, neutral "
            f"expression, soft even lighting on the face, {QUALITY_SUFFIX}"
        ),
    }


def _slot_brief(index: int, slot: BeatSlot) -> str:
    if slot.internal_cut_frames is None:
        return f"{slot.duration_s:.1f} s, 1 sub-shot"
    first = slot.internal_cut_frames / 24
    return f"{slot.duration_s:.1f} s, 2 sub-shots: {first:.1f} s then {slot.duration_s - first:.1f} s"


# ------------------------------------------------------------------------- convert


async def write_screenplay(
    text: str, client: LlmClient | None, *, attempts: int = 2
) -> tuple[Screenplay, str]:
    """Premise -> `Screenplay`. Returns `(screenplay, how)`; raises `ScreenplayError`.

    `how` is "llm" or "llm-retry" (the outline or a shots call needed a second
    try). There is deliberately no client-less path: with no screenwriter
    there is no drama, and saying so costs nothing.
    """
    if client is None:
        raise ScreenplayError("no screenwriter available (the pod's gpt-oss-20b is required)")

    premise = text.strip()
    retried = False

    outline_user = f"Premise: {premise}\nReply with the JSON object only."
    outline, was_retry = await _ask(
        client, OUTLINE_SYSTEM, outline_user, OUTLINE_MAX_TOKENS, build_outline, attempts
    )
    retried |= was_retry
    anchor: CharacterAnchor = outline["anchor"]
    world: WorldBible = outline["world"]

    shots: list[DramaShot] = []
    half = SHOT_COUNT // 2
    for expected in ([*range(1, half + 1)], [*range(half + 1, SHOT_COUNT + 1)]):
        beats = "\n".join(
            f"Shot {i} ({BEAT_TEMPLATE[i - 1].beat.value.upper()}, {_slot_brief(i, BEAT_TEMPLATE[i - 1])}): "
            f"{outline['beats'][i - 1]}"
            for i in expected
        )
        seam = ""
        if shots:
            seam = f"The previous shot ended on a {shots[-1].sub_shots[-1].framing.value} framing; do not start with it.\n"
        user = (
            f"Title: {outline['title']}\nLogline: {outline['logline']}\n"
            f"Style: {outline['style']}\n"
            f"The lead is {anchor.name} (appearance is supplied separately -- do not describe it).\n"
            f"Location and light are supplied separately -- do not repeat them.\n"
            f"{seam}"
            f"Shots to write:\n{beats}\n"
            "Reply with the JSON object only."
        )
        built, was_retry = await _ask(
            client, SHOTS_SYSTEM, user, SHOTS_MAX_TOKENS,
            lambda payload, exp=expected: build_shots(payload, expected=exp, anchor=anchor, world=world),
            attempts,
        )
        retried |= was_retry
        shots.extend(built)

    try:
        screenplay = Screenplay(
            title=outline["title"],
            logline=outline["logline"],
            style=outline["style"],
            anchor=anchor,
            world=world,
            beats={slot.beat: text for slot, text in zip(BEAT_TEMPLATE, outline["beats"], strict=True)},
            shots=tuple(shots),
            overall_soundscape=outline["overall_soundscape"],
            non_diegetic_music=outline["non_diegetic_music"],
        )
    except ValidationError as exc:
        raise ScreenplayError(f"screenplay failed validation: {exc}") from exc
    return screenplay, "llm-retry" if retried else "llm"


async def _ask(
    client: LlmClient, system: str, user: str, max_tokens: int, build: Any, attempts: int
) -> tuple[Any, bool]:
    """Up to `attempts` tries; a retry restates the exact violation, not the
    same prompt again. 📏 2026-08-29 (job 107): the model wrote the
    cliffhanger as a bare prop shot on both attempts, in the same words,
    because nothing told it what it had done wrong the second time. A
    validator that repeats a systematic mistake back at itself catches
    nothing; one that is told the specific rule it broke usually fixes it."""
    last = ""
    for attempt in range(attempts):
        prompt = user if attempt == 0 else (
            f"{user}\n\nYour previous reply was invalid: {last}\n"
            "Fix exactly that and reply with the corrected JSON object only."
        )
        try:
            reply = await client.complete(system, prompt, max_tokens=max_tokens)
            return build(extract_json(reply)), attempt > 0
        except ScreenplayError as exc:
            last = str(exc)
        except Exception as exc:  # the convert module's own parse error, network, timeout
            last = f"{type(exc).__name__}: {exc}"
    raise ScreenplayError(f"screenwriter failed after {attempts} attempts: {last[:300]}")


# ------------------------------------------------------------------------ renderers

SILENT = ". The lead is not speaking and their lips remain closed"


def h3_prompt(shot: DramaShot, screenplay: Screenplay, *, subshots: bool = True) -> H3Prompt:
    """The image-to-video prompt for one shot, in the official H3 schema.

    Same shape `/圖影` produces: the keyframe is Picture 1 and the opening
    frame, so the first sub-shot states that role and then the action -- with
    the world bible and the anchor pasted in once more, verbatim, because
    restating the subject at every cut is the guide's own rule against face
    drift. A second sub-shot becomes a second `PromptShot` cutting at the
    template's time; `subshots=False` folds it into one held shot (the
    hedge for a model that ignores `cut_at_s` under image-to-video).
    """
    anchor, world = screenplay.anchor, screenplay.world
    subject = f"{anchor.appearance}, wearing {anchor.wardrobe}"

    def dialogue(sub: SubShot) -> tuple[Dialogue, ...]:
        return tuple(
            Dialogue(speaker_id=line.speaker_id, identity=line.identity, language=line.language, text=line.text)
            for line in sub.dialogue
        )

    first = shot.sub_shots[0]
    description = (
        "Picture 1 is the opening frame; keep the same person, clothing, setting and "
        f"framing. {world.prefix()}. {subject}, in a {first.framing.value} shot: {first.action.rstrip('.')}"
    )
    if not first.dialogue:
        description += SILENT
    prompt_shots = [
        PromptShot(index=1, style=screenplay.style, description=description, camera=first.camera, dialogue=dialogue(first))
    ]
    rest = shot.sub_shots[1:]
    if rest and subshots and shot.internal_cut_s is not None:
        second = rest[0]
        text = f"{subject}, same setting, in a {second.framing.value} shot: {second.action.rstrip('.')}"
        if not second.dialogue:
            text += SILENT
        prompt_shots.append(
            PromptShot(index=2, cut_at_s=shot.internal_cut_s, description=text, camera=second.camera, dialogue=dialogue(second))
        )
    elif rest:
        # One held shot: the second action continues the first, and any line
        # it carried is still spoken.
        second = rest[0]
        merged = description.removesuffix(SILENT) + f"; then {second.action.rstrip('.')}"
        lines = dialogue(first) + dialogue(second)
        if not lines:
            merged += SILENT
        prompt_shots = [
            PromptShot(index=1, style=screenplay.style, description=merged, camera=first.camera, dialogue=lines)
        ]
    return H3Prompt(
        mode=H3Mode.I2VA,
        duration_s=shot.duration_s,
        shots=tuple(prompt_shots),
        overall_soundscape=screenplay.overall_soundscape,
        non_diegetic_music=screenplay.non_diegetic_music,
    )


def screenplay_payload(screenplay: Screenplay, how: str) -> dict[str, Any]:
    """What goes into `jobs.prompt_json` for a drama.

    `shots` is shaped like the H3 plan's shots (`index`, `description`) so the
    status page's existing breakdown renders it; the full screenplay rides
    under its own key for the render.
    """
    return {
        "_built_by": how,
        "_rendered": f"{screenplay.title} -- {screenplay.logline}",
        "screenplay": json.loads(screenplay.model_dump_json()),
        "shots": [
            {
                "index": s.index,
                "description": (
                    f"[{s.beat.value} {s.duration_s:.1f}s] "
                    + " | ".join(f"[{sub.framing.value}] {sub.action}" for sub in s.sub_shots)
                    + f" -- {s.scene}"
                ),
            }
            for s in screenplay.shots
        ],
    }
