"""A minimal *text* interviewer — the 2026-08-30 stand-in for INTERVIEW.md
§6's voice-to-voice AI interviewer (Phase 3-B, never built; see twin/PLAN.md
Phase 3 for the decision and what it costs).

What it keeps from INTERVIEW.md: the §4 schedule and every required coverage
point, in order; a single continuous session with a real clock; follow-ups
generated by the Teacher until a point reaches concrete instances (§2:
"訪談員必須追問", §6.1: no options, no leading, adjectives don't count); a
full transcript of *both* speakers (§2 "逐字稿...含受訪者與訪談員雙方發言").

What it gives up, deliberately and visibly: voice (§6 形式), the 102-120 min
duration and 5,500-char floor (§3.1) are measured at ingest by
`ingest.quality_check` and will very likely fail — §7 says that marks the
suite low-confidence, it does not block. Q8 (third-party tagging) is not
this module's concern: it happens at ingest in
`ingest.sources.interview_transcript`, structurally.

I/O is injected (`ask`), so the session logic is testable with a fake
Teacher and scripted answers; `examples/run_text_interview.py` binds it to
the terminal.
"""

from __future__ import annotations

from collections.abc import Callable
from datetime import UTC, datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict

from twin.ingest.interview_schedule import (
    BLOCK_OPENINGS,
    BLOCK_ORDER,
    CoveragePoint,
    points_in_block,
)
from twin.teacher.base import Teacher, TeacherError

Speaker = Literal["interviewer", "respondent"]

MAX_FOLLOW_UPS_PER_POINT = 2


class Turn(BaseModel):
    model_config = ConfigDict(frozen=True)

    speaker: Speaker
    block: str
    point_id: str | None  # None for a block opening line
    text: str
    at: datetime


class InterviewTranscript(BaseModel):
    """The whole session, verbatim. `notes` records anything the interviewer
    could not do (e.g. Teacher quota exhausted mid-session) so the ingest
    side can see it — INTERVIEW.md §7's confidence marking needs to know
    when follow-ups silently stopped."""

    model_config = ConfigDict(frozen=True)

    principal_id: str
    mode: Literal["text"]
    started_at: datetime
    ended_at: datetime
    turns: list[Turn]
    notes: list[str]

    def block_texts(self) -> dict[str, str]:
        """Both speakers, per block, in order — the `blocks` argument
        `ingest.sources.interview_transcript.fragments_from_interview_transcript`
        takes. Speaker labels are part of the transcript, not decoration:
        INTERVIEW.md §2 defines a transcript as containing both sides."""
        out: dict[str, list[str]] = {}
        for turn in self.turns:
            label = "訪談員" if turn.speaker == "interviewer" else "本人"
            out.setdefault(turn.block, []).append(f"{label}：{turn.text}")
        return {block: "\n".join(lines) for block, lines in out.items() if lines}

    def speaker_turns(self) -> list[tuple[str, str]]:
        """`ingest.quality_check.check_q5_speaker_ratio`'s input shape."""
        return [(turn.speaker, turn.text) for turn in self.turns]

    def full_text(self) -> str:
        return "\n\n".join(f"【區塊 {block}】\n{text}" for block, text in self.block_texts().items())


class FollowUpDecision(BaseModel):
    """What the Teacher returns after seeing one coverage point's exchange so
    far. `follow_up_question` MUST be open-ended and offer no options
    (INTERVIEW.md §6.1) — the prompt says so; this schema cannot enforce it."""

    model_config = ConfigDict(frozen=True)

    concrete_instances: int
    reached: bool
    follow_up_question: str | None


def _follow_up_prompt(point: CoveragePoint, exchange: list[Turn]) -> str:
    transcript = "\n".join(
        ("訪談員：" if t.speaker == "interviewer" else "本人：") + t.text for t in exchange
    )
    return (
        "你是一位半結構化訪談的訪談員，正在對一位受訪者進行人生敘事與行為政策訪談。\n"
        f"目前的必達點是 {point.point_id}：「{point.question}」\n"
        f"這個必達點需要至少 {point.required_instances} 個具體事例"
        "（具體事例 = 有時間、有地點或對象、有結果的真實事件；「我很懶」這類形容詞不算）。\n"
        "請依下面目前為止的對話判斷：(1) 受訪者已經給出幾個具體事例；(2) 必達點是否已達成；"
        "(3) 若未達成，寫一句開放式追問，把受訪者剛才的回答追到事例層級。\n"
        "追問規則：MUST 開放式；MUST NOT 提供選項；MUST NOT 誘導或替受訪者總結；"
        "一次只問一個問題；用台灣華語口語；不超過 40 字。若已達成，follow_up_question 為 null。\n\n"
        f"目前為止的對話：\n{transcript}"
    )


class TextInterviewer:
    def __init__(
        self,
        *,
        teacher: Teacher,
        ask: Callable[[str], str],
        clock: Callable[[], datetime] = lambda: datetime.now(UTC),
        max_follow_ups: int = MAX_FOLLOW_UPS_PER_POINT,
    ) -> None:
        self._teacher = teacher
        self._ask = ask
        self._clock = clock
        self._max_follow_ups = max_follow_ups

    def run(self, *, principal_id: str) -> InterviewTranscript:
        turns: list[Turn] = []
        notes: list[str] = []
        started_at = self._clock()

        def say(block: str, point_id: str | None, text: str) -> str:
            turns.append(Turn(speaker="interviewer", block=block, point_id=point_id, text=text, at=self._clock()))
            answer = self._ask(text).strip()
            turns.append(Turn(speaker="respondent", block=block, point_id=point_id, text=answer, at=self._clock()))
            return answer

        def respondent_share(block_turns: list[Turn]) -> float:
            total = sum(len(t.text) for t in block_turns)
            return sum(len(t.text) for t in block_turns if t.speaker == "respondent") / total if total else 1.0

        def follow_up_round(point: CoveragePoint, exchange_start: int, block: str) -> bool:
            """One Teacher judgement + at most one follow-up; True when the point is reached."""
            try:
                decision = self._teacher.generate(
                    _follow_up_prompt(point, turns[exchange_start:]), response_schema=FollowUpDecision
                )
            except TeacherError as exc:
                notes.append(f"{point.point_id}: follow-up skipped, Teacher unavailable ({exc})")
                return True  # cannot judge — stop asking, not "reached"; the note records it
            if decision.reached or not decision.follow_up_question:
                return True
            say(block, point.point_id, decision.follow_up_question)
            return False

        for block in BLOCK_ORDER:
            block_start = len(turns)
            opening = BLOCK_OPENINGS[block]
            if block == "A":
                # §4 A: the opening line IS the first question, and it MUST be
                # this open-ended one — A1 follows once the story has been told.
                say(block, None, opening)
            else:
                turns.append(Turn(speaker="interviewer", block=block, point_id=None, text=opening, at=self._clock()))
            unreached: dict[str, int] = {}  # point_id -> index of its first turn
            block_points = points_in_block(block)
            for i, point in enumerate(block_points):
                exchange_start = len(turns)
                say(block, point.point_id, point.question)
                if point.required_instances == 0:
                    continue
                reached = False
                for _ in range(self._max_follow_ups):
                    if follow_up_round(point, exchange_start, block):
                        reached = True
                        break
                if not reached:
                    unreached[point.point_id] = exchange_start
                if i == len(block_points) // 2 and respondent_share(turns[block_start:]) < 0.7:
                    # INTERVIEW.md §7 Q5: "訪談員 MUST 於每區塊中段自我檢核發言占比"
                    notes.append(f"block {block}: respondent share below 70% at mid-block")
            # INTERVIEW.md §6.1: "每區塊結束前 MUST 自我檢核必達點，未達成者 MUST 於同場次內補問"
            # — one in-session probe per still-unreached point, then move on regardless (D35: no re-interview).
            for point_id, exchange_start in unreached.items():
                point = next(p for p in block_points if p.point_id == point_id)
                if not follow_up_round(point, exchange_start, block):
                    notes.append(f"{point_id}: not reached after block-end probe (INTERVIEW.md §7 Q1/Q2 low confidence)")

        return InterviewTranscript(
            principal_id=principal_id,
            mode="text",
            started_at=started_at,
            ended_at=self._clock(),
            turns=turns,
            notes=notes,
        )
