"""The `/短劇` screenwriter: one story premise -> a validated `Screenplay`.

Pure, like `prompts.convert`: takes an `LlmClient`, does no I/O of its own,
and everything the model returns goes through pydantic before it can spend a
GPU-second. Three calls rather than one, because the pod's inference server
caps a json-only reply at `MAX_NEW_TOKENS_CEILING` (1536 tokens) and six full
shots plus a character sheet do not reliably fit:

1. **outline** -- title, logline, style, the `CharacterAnchor`, six beats.
2. **shots 1-3** and 3. **shots 4-6** -- each beat expanded into a shot,
   with the anchor handed back in so the model has no reason to re-invent it.

**No template fallback.** `prompts.convert` degrades to a one-line template
because a mediocre clip beats a dropped request. A drama is different: a
"template" would be six clips of nothing in particular, at six times the
cost. `write_screenplay` raises `ScreenplayError` and the job fails loudly.

**The anchor is composed here, not by the model.** The keyframe prompt is
`appearance + wardrobe + framing + scene`, assembled in `keyframe_prompt()`,
so the verbatim-anchor rule `core.drama_spec.Screenplay` enforces is met by
construction. The model writes the scene; it does not get to write the face.
"""

from __future__ import annotations

import json
from typing import Any, Protocol

from pydantic import ValidationError

from ai_studio.core.drama_spec import (
    SHOT_COUNT,
    CharacterAnchor,
    DramaLine,
    DramaShot,
    Screenplay,
)
from ai_studio.core.enums import TransitionReason
from ai_studio.prompts.convert import camera_from_spec, extract_json
from ai_studio.prompts.flux import QUALITY_SUFFIX
from ai_studio.prompts.h3 import Dialogue, H3Mode, H3Prompt, PromptShot


class LlmClient(Protocol):
    async def complete(self, system: str, user: str, *, max_tokens: int = 1200) -> str: ...


class ScreenplayError(Exception):
    """The screenwriter could not produce a valid screenplay. Terminal."""


OUTLINE_MAX_TOKENS = 900
SHOTS_MAX_TOKENS = 1400
"""Under the inference server's 1536 ceiling with room for the harmony
channel markers. Both `[speculative]` until a real token count is measured."""

OUTLINE_SYSTEM = """\
You are a screenwriter for one-minute short dramas generated by a video model.
Reply with JSON only, no prose and no code fence.

Schema:
{
  "title": "<short title, may be Chinese>",
  "logline": "<one sentence: who wants what, what stands in the way>",
  "style": "<visual style, e.g. 'Live-action, cinematic' or '2D-animated'>",
  "anchor": {
    "name": "<the lead's name>",
    "appearance": "<English. 12-30 words of CONCRETE, STABLE facial and hair \
features: age, ethnicity, face shape, one distinguishing mark, hair colour, \
length and style. Example: '25-year-old Asian woman, oval face, small mole under \
right eye, dark chin-length straight hair'. No mood words, no beauty words.>",
    "wardrobe": "<English. What the lead wears for the whole drama.>",
    "voice": "<English. How the lead sounds, e.g. 'soft, low, slightly hoarse'.>"
  },
  "beats": ["<beat 1>", "<beat 2>", "<beat 3>", "<beat 4>", "<beat 5>", "<beat 6>"],
  "overall_soundscape": "<1-3 English sentences: ambience and action sounds shared \
by the whole drama>",
  "non_diegetic_music": "<1-2 English sentences on instrumentation, tempo and \
dynamics, or exactly N/A>"
}

Rules:
- Exactly 6 beats, each one English sentence: setup, complication, turn,
  escalation, climax, resolution. One lead character throughout; other people
  may appear but stay unnamed and in the background.
- The premise is the spec. Keep every concrete thing the user named (places,
  objects, names, moods) and invent only what is needed to make six beats.
- appearance/wardrobe/voice are English and concrete. Never describe the face
  anywhere else than in "appearance".
"""

SHOTS_SYSTEM = """\
You expand story beats into shots for the MiniMax H3 video model. Each shot is
about 10 seconds, rendered from a still first frame. Reply with JSON only, no
prose and no code fence.

Schema:
{
  "shots": [
    {
      "index": <the beat number given>,
      "scene": "<English. Setting, time of day, light, key props around the \
lead. Concrete and visible. Do NOT describe the lead's face or hair.>",
      "framing": "<one of: wide, medium, medium close-up, close-up, \
over-the-shoulder, two-shot>",
      "action": "<English. The ONE thing the lead does in these 10 seconds, \
as a visible action, restating 'the lead' rather than any face words.>",
      "camera": {
        "motion": "<one of: zoom_in zoom_out push_in pull_out pan_left pan_right \
truck_left truck_right tilt_up tilt_down pedestal_up pedestal_down arc_shot \
tracking_shot static_shot shake_slightly pov>",
        "amplitude": "<small|medium|large>",
        "speed": "<slow|normal|fast>",
        "toward": "<optional: what the camera moves toward>"
      },
      "dialogue": [
        {"speaker_id": "S1", "identity": "<who and how they sound>",
         "language": "<Mandarin Chinese|English|...>", "text": "<the exact words>"}
      ],
      "cut_reason": "<default|time_passing|topic_change|drill_down>"
    }
  ]
}

Rules:
- One shot per beat, in the order given, with the given index.
- Alternate framing between consecutive shots (never the same framing twice in
  a row); prefer medium / close-up / over-the-shoulder so the lead is
  re-established each cut.
- At most one dialogue line per shot, 4-14 words, only when the beat implies
  speech. Otherwise omit "dialogue" and the lead is silent with lips closed.
- Never mention the lead's face, hair, age or ethnicity: the appearance is
  supplied separately and pasted in verbatim. Refer to "the lead".
- Everything is English except the dialogue text, which stays in the
  premise's language.
"""

_CUT_REASONS = {r.value: r for r in TransitionReason}


# ------------------------------------------------------------------------ builders


def build_outline(payload: dict[str, Any]) -> dict[str, Any]:
    """Validate the outline reply into its typed parts. Raises `ScreenplayError`."""
    beats = payload.get("beats")
    if not isinstance(beats, list) or len(beats) != SHOT_COUNT:
        raise ScreenplayError(f"outline needs exactly {SHOT_COUNT} beats, got {beats!r}")
    if not all(isinstance(b, str) and b.strip() for b in beats):
        raise ScreenplayError("every beat must be a non-empty string")
    try:
        anchor = CharacterAnchor.model_validate(payload.get("anchor") or {})
    except ValidationError as exc:
        raise ScreenplayError(f"invalid character anchor: {exc}") from exc
    title = str(payload.get("title") or "").strip()
    logline = str(payload.get("logline") or "").strip()
    if not title or not logline:
        raise ScreenplayError("outline needs a title and a logline")
    return {
        "title": title,
        "logline": logline,
        "style": str(payload.get("style") or "Live-action, cinematic").strip(),
        "anchor": anchor,
        "beats": [b.strip() for b in beats],
        "overall_soundscape": str(payload.get("overall_soundscape") or "").strip()
        or "Quiet ambient room tone with the lead's own movement audible over it.",
        "non_diegetic_music": str(payload.get("non_diegetic_music") or "N/A").strip(),
    }


def _lines(items: Any) -> tuple[DramaLine, ...]:
    out: list[DramaLine] = []
    for item in items if isinstance(items, list) else []:
        if not isinstance(item, dict) or not item.get("text"):
            continue
        try:
            out.append(
                DramaLine(
                    speaker_id=str(item.get("speaker_id") or "S1"),
                    identity=str(item.get("identity") or "the lead"),
                    language=str(item.get("language") or "Mandarin Chinese"),
                    text=str(item["text"]),
                )
            )
        except ValidationError:
            continue  # a malformed line loses the line, not the shot
    return tuple(out[:1])  # at most one line per 10 s shot


def build_shots(
    payload: dict[str, Any], *, expected: list[int], anchor: CharacterAnchor
) -> list[DramaShot]:
    """Validate one shots reply for the given beat indices. Raises `ScreenplayError`."""
    raw = payload.get("shots")
    if not isinstance(raw, list) or len(raw) != len(expected):
        raise ScreenplayError(f"expected shots {expected}, got {len(raw) if isinstance(raw, list) else raw!r}")
    shots: list[DramaShot] = []
    for index, spec in zip(expected, raw, strict=True):
        if not isinstance(spec, dict):
            raise ScreenplayError(f"shot {index} was not an object")
        scene = str(spec.get("scene") or "").strip()
        framing = str(spec.get("framing") or "medium").strip()
        action = str(spec.get("action") or "").strip()
        if not scene or not action:
            raise ScreenplayError(f"shot {index} needs a scene and an action")
        try:
            shots.append(
                DramaShot(
                    index=index,
                    scene=scene,
                    framing=framing,
                    action=action,
                    keyframe_prompt=keyframe_prompt(anchor, framing=framing, scene=scene),
                    camera=camera_from_spec(spec.get("camera")),
                    dialogue=_lines(spec.get("dialogue")),
                    cut_reason=_CUT_REASONS.get(
                        str(spec.get("cut_reason") or "default"), TransitionReason.DEFAULT
                    ),
                )
            )
        except ValidationError as exc:
            raise ScreenplayError(f"shot {index} failed validation: {exc}") from exc
    return shots


def keyframe_prompt(anchor: CharacterAnchor, *, framing: str, scene: str) -> str:
    """The Flux prompt for a shot's still first frame.

    Anchor first and verbatim, then wardrobe, framing, scene, then the same
    quality tail `/圖片` uses. Composed here so no model output can drop it.
    """
    return (
        f"{anchor.appearance}, wearing {anchor.wardrobe}, {framing} shot, "
        f"{scene.rstrip('.')}, {QUALITY_SUFFIX}"
    )


def character_sheet_prompts(anchor: CharacterAnchor) -> dict[str, str]:
    """The two reference stills every keyframe is repainted from."""
    base = f"{anchor.appearance}, wearing {anchor.wardrobe}"
    return {
        "front": (
            f"{base}, front-facing head-and-shoulders portrait, neutral expression, "
            f"plain grey studio background, soft even lighting, {QUALITY_SUFFIX}"
        ),
        "three_quarter": (
            f"{base}, three-quarter view portrait turned slightly left, neutral "
            f"expression, plain grey studio background, soft even lighting, {QUALITY_SUFFIX}"
        ),
    }


# ------------------------------------------------------------------------- convert


async def write_screenplay(
    text: str, client: LlmClient | None, *, attempts: int = 2
) -> tuple[Screenplay, str]:
    """Premise -> `Screenplay`. Returns `(screenplay, how)`; raises `ScreenplayError`.

    `how` is "llm" or "llm-retry" (the outline or a shots call needed a second
    try). There is deliberately no client-less path: with no screenwriter
    there is no drama, and saying so costs nothing.
    """
    if client is None:
        raise ScreenplayError("no screenwriter available (the pod's gpt-oss-20b is required)")

    premise = text.strip()
    retried = False

    outline_user = f"Premise: {premise}\nReply with the JSON object only."
    outline, was_retry = await _ask(
        client, OUTLINE_SYSTEM, outline_user, OUTLINE_MAX_TOKENS, build_outline, attempts
    )
    retried |= was_retry
    anchor: CharacterAnchor = outline["anchor"]

    shots: list[DramaShot] = []
    half = SHOT_COUNT // 2
    for expected in ([*range(1, half + 1)], [*range(half + 1, SHOT_COUNT + 1)]):
        beats = "\n".join(f"{i}. {outline['beats'][i - 1]}" for i in expected)
        user = (
            f"Title: {outline['title']}\nLogline: {outline['logline']}\n"
            f"Style: {outline['style']}\n"
            f"The lead is {anchor.name} (appearance is supplied separately -- do not describe it).\n"
            f"Beats to expand, one shot each:\n{beats}\n"
            "Reply with the JSON object only."
        )
        built, was_retry = await _ask(
            client, SHOTS_SYSTEM, user, SHOTS_MAX_TOKENS,
            lambda payload, exp=expected: build_shots(payload, expected=exp, anchor=anchor),
            attempts,
        )
        retried |= was_retry
        shots.extend(built)

    try:
        screenplay = Screenplay(
            title=outline["title"],
            logline=outline["logline"],
            style=outline["style"],
            anchor=anchor,
            shots=tuple(shots),
            overall_soundscape=outline["overall_soundscape"],
            non_diegetic_music=outline["non_diegetic_music"],
        )
    except ValidationError as exc:
        raise ScreenplayError(f"screenplay failed validation: {exc}") from exc
    return screenplay, "llm-retry" if retried else "llm"


async def _ask(
    client: LlmClient, system: str, user: str, max_tokens: int, build: Any, attempts: int
) -> tuple[Any, bool]:
    last = ""
    for attempt in range(attempts):
        try:
            reply = await client.complete(system, user, max_tokens=max_tokens)
            return build(extract_json(reply)), attempt > 0
        except ScreenplayError as exc:
            last = str(exc)
        except Exception as exc:  # the convert module's own parse error, network, timeout
            last = f"{type(exc).__name__}: {exc}"
    raise ScreenplayError(f"screenwriter failed after {attempts} attempts: {last[:300]}")


# ------------------------------------------------------------------------ renderers


def h3_prompt(shot: DramaShot, screenplay: Screenplay, *, duration_s: float) -> H3Prompt:
    """The image-to-video prompt for one shot, in the official H3 schema.

    Same shape `/圖影` produces: the keyframe is Picture 1 and the opening
    frame, so the description states that role and then the action -- with
    the anchor pasted in once more, verbatim, because restating the subject
    at every cut is the guide's own rule against face drift.
    """
    anchor = screenplay.anchor
    description = (
        "Picture 1 is the opening frame; keep the same person, clothing, setting and "
        f"framing. {anchor.appearance}, wearing {anchor.wardrobe}, in a {shot.framing} "
        f"shot: {shot.action.rstrip('.')}"
    )
    dialogue = tuple(
        Dialogue(
            speaker_id=line.speaker_id,
            identity=line.identity if line.identity else f"{anchor.name}, {anchor.voice}",
            language=line.language,
            text=line.text,
        )
        for line in shot.dialogue
    )
    if not dialogue:
        description += ". The lead is not speaking and their lips remain closed"
    return H3Prompt(
        mode=H3Mode.I2VA,
        duration_s=duration_s,
        shots=(
            PromptShot(
                index=1,
                style=screenplay.style,
                description=description,
                camera=shot.camera,
                dialogue=dialogue,
            ),
        ),
        overall_soundscape=screenplay.overall_soundscape,
        non_diegetic_music=screenplay.non_diegetic_music,
    )


def screenplay_payload(screenplay: Screenplay, how: str) -> dict[str, Any]:
    """What goes into `jobs.prompt_json` for a drama.

    `shots` is shaped like the H3 plan's shots (`index`, `description`) so the
    status page's existing breakdown renders it; the full screenplay rides
    under its own key for the render.
    """
    return {
        "_built_by": how,
        "_rendered": f"{screenplay.title} -- {screenplay.logline}",
        "screenplay": json.loads(screenplay.model_dump_json()),
        "shots": [
            {"index": s.index, "description": f"[{s.framing}] {s.action} -- {s.scene}"}
            for s in screenplay.shots
        ],
    }
