"""S1 — persona fidelity. EVAL.md §3. twin/PLAN.md Phase 2: the item bank is
generated by exactly one batched Teacher call against real `Split.HELDOUT`
fragments (D9: 少次、大批 — this function makes at most one `teacher.generate()`
call, ever, with no retry logic), then frozen (`harness.item_bank`) before
Wave 1 (R1) answers are collected. Nothing after freezing may edit an item
without changing its id and therefore the whole bank's hash.

EVAL.md §9 data-hygiene rule (not enforced here — no Fragment-level field
exists yet to check against): the Teacher call batch that produces S1 items
MUST NOT share source fragments with any call that produces training
trajectories. That's a caller responsibility (how `held_out_fragment_ids` is
chosen), not something this function can verify.
"""

from __future__ import annotations

import hashlib
import json
from typing import Literal

from pydantic import BaseModel, Field

from twin.core.enums import Split
from twin.core.fragment import Fragment
from twin.harness.schema import HarnessError, S1Item
from twin.ingest.store import read_fragments_jsonl
from twin.teacher import Teacher, TeacherError

MIN_ITEMS = 60
MAX_ITEMS = 80

# EVAL.md §3.2's 30/25/25/20 SHOULD ratio, applied to a target total of 70
# (the midpoint of the 60-80 MUST range) purely to give the prompt concrete
# per-category counts instead of vague percentages. Guidance only — the
# actual returned ratio is never enforced, only the total count is (see
# build_item_bank). Sums to 70.
_TARGET_COUNTS = {
    "value_tradeoff": 21,
    "preference": 18,
    "reaction_tendency": 17,
    "recall": 14,
}

# Conservative, UNVERIFIED guess at a safe prompt size for the configured
# Gemini Flash model's context window with headroom for the response — not
# checked against a real account/model limit. Exists so an oversized prompt
# fails loudly before the one real teacher.generate() call, never after it
# has already burned a unit of the daily quota.
_MAX_PROMPT_CHARS = 60_000


class _GeneratedItem(BaseModel):
    prompt: str
    options: list[str] = Field(min_length=2)
    source_fragment_ids: list[str] = Field(min_length=1)


class _ItemBankResponse(BaseModel):
    """Separate typed lists per category, not one flat list + post-hoc
    filtering — gives the model's structured-output mode a stronger
    per-category signal, and makes "which item_type is this" structural
    rather than something it also has to get right inside a flat object."""

    value_tradeoff: list[_GeneratedItem]
    preference: list[_GeneratedItem]
    reaction_tendency: list[_GeneratedItem]
    recall: list[_GeneratedItem]


def _load_held_out_fragments(fragment_ids: list[str], *, fragment_store_uri: str) -> list[Fragment]:
    wanted = set(fragment_ids)
    found: dict[str, Fragment] = {}
    for fragment in read_fragments_jsonl(fragment_store_uri):
        if fragment.fragment_id in wanted:
            found[fragment.fragment_id] = fragment

    missing = wanted - found.keys()
    if missing:
        raise HarnessError(f"held_out_fragment_ids not found in {fragment_store_uri}: {sorted(missing)}")

    non_heldout = [fid for fid, fragment in found.items() if fragment.split != Split.HELDOUT]
    if non_heldout:
        raise HarnessError(
            "EVAL.md §3.1/§9, anti-pattern #7: S1 items MUST be built only from "
            f"Split.HELDOUT fragments (never train/sealed) — got non-heldout ids: {sorted(non_heldout)}"
        )

    return [found[fid] for fid in fragment_ids]  # preserve caller-given order


def _render_prompt(fragments: list[Fragment]) -> str:
    lines = [
        "你是在為本人（principal）建立一份人格保真度測驗（EVAL.md §3.2）。",
        "以下是本人 held-out 時段的真實資料片段，每則格式為",
        "[fragment_id] (event_time, precision) content：",
        "",
    ]
    for fragment in fragments:
        marker = " [第三方內容，僅供脈絡，勿逐字引用]" if fragment.third_party_spans else ""
        lines.append(
            f"[{fragment.fragment_id}] ({fragment.event_time.value}, "
            f"precision={fragment.event_time.precision.value}){marker} {fragment.content}"
        )
    lines += [
        "",
        "請生成共 60–80 題情境題，格式僅限單選或李克特量表（每題至少 2 個選項）。",
        "四種題型與建議題數（比例為 SHOULD，非強制精確）：",
        f"- value_tradeoff（價值取捨：兩個都合理的選項二選一）約 {_TARGET_COUNTS['value_tradeoff']} 題",
        f"- preference（偏好：工具、做法、風格的選擇）約 {_TARGET_COUNTS['preference']} 題",
        f"- reaction_tendency（反應傾向：看到 X 你會不會做 Y）約 {_TARGET_COUNTS['reaction_tendency']} 題",
        f"- recall（回想：需能從上面片段準確回想具體內容）約 {_TARGET_COUNTS['recall']} 題",
        "",
        "規則（MUST）：",
        "1. 每題描述的情境本人從未明確表態過——recall 題除外，其目的正是測試能否",
        "   準確回想片段中的內容（EVAL.md §3.1）。",
        "2. 每題的 source_fragment_ids 只能引用上面實際列出的 fragment_id，不可捏造。",
        "3. 每題至少 2 個選項；李克特題請用完整量表標籤（例如：非常不同意/不同意/普通/同意/非常同意）。",
    ]
    prompt = "\n".join(lines)
    if len(prompt) > _MAX_PROMPT_CHARS:
        raise HarnessError(
            f"rendered prompt is {len(prompt)} chars, over the {_MAX_PROMPT_CHARS}-char "
            f"guard — reduce held_out_fragment_ids before calling build_item_bank again "
            f"(a guess must never be resolved by silently truncating the prompt)"
        )
    return prompt


def _item_id(*, item_type: str, prompt: str, options: list[str], source_fragment_ids: list[str]) -> str:
    """Content-derived, same pattern as `harness.shard.sample_id` — makes
    `harness.item_bank.bank_hash` content-sensitive for free."""
    canonical = json.dumps(
        {
            "item_type": item_type,
            "prompt": prompt,
            "options": options,
            "source_fragment_ids": sorted(source_fragment_ids),
        },
        sort_keys=True,
        ensure_ascii=False,
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()[:16]


def _to_items(
    item_type: Literal["value_tradeoff", "preference", "reaction_tendency", "recall"],
    generated_items: list[_GeneratedItem],
    *,
    valid_fragment_ids: set[str],
) -> list[S1Item]:
    items: list[S1Item] = []
    for generated in generated_items:
        cited = set(generated.source_fragment_ids)
        if not cited <= valid_fragment_ids:
            raise TeacherError(
                f"generated {item_type} item cites fragment id(s) outside the held-out "
                f"set it was given: {sorted(cited - valid_fragment_ids)}"
            )
        items.append(
            S1Item(
                item_id=_item_id(
                    item_type=item_type,
                    prompt=generated.prompt,
                    options=generated.options,
                    source_fragment_ids=generated.source_fragment_ids,
                ),
                item_type=item_type,
                prompt=generated.prompt,
                options=generated.options,
                source_fragment_ids=generated.source_fragment_ids,
            )
        )
    return items


def build_item_bank(*, held_out_fragment_ids: list[str], teacher: Teacher, fragment_store_uri: str) -> list[S1Item]:
    if not held_out_fragment_ids:
        raise HarnessError("held_out_fragment_ids is empty — nothing to build an item bank from")

    fragments = _load_held_out_fragments(held_out_fragment_ids, fragment_store_uri=fragment_store_uri)
    prompt = _render_prompt(fragments)  # raises HarnessError before any Teacher call if oversized
    valid_ids = {fragment.fragment_id for fragment in fragments}

    response = teacher.generate(prompt, response_schema=_ItemBankResponse)  # exactly one call — D9

    bank: list[S1Item] = [
        *_to_items("value_tradeoff", response.value_tradeoff, valid_fragment_ids=valid_ids),
        *_to_items("preference", response.preference, valid_fragment_ids=valid_ids),
        *_to_items("reaction_tendency", response.reaction_tendency, valid_fragment_ids=valid_ids),
        *_to_items("recall", response.recall, valid_fragment_ids=valid_ids),
    ]

    if not (MIN_ITEMS <= len(bank) <= MAX_ITEMS):
        raise TeacherError(f"generated {len(bank)} items — EVAL.md §3.2 requires {MIN_ITEMS}-{MAX_ITEMS}")

    ids = [item.item_id for item in bank]
    if len(set(ids)) != len(ids):
        raise TeacherError("generated item bank contains duplicate items (identical type/prompt/options/citations)")

    return bank
