"""S1 — persona fidelity. EVAL.md §3. Sample construction needs a real Teacher
call against real held-out fragments (twin/PLAN.md Phase 2) — deferred; the
real machinery it will consume already exists (`harness.schema.S1Item`,
`harness.aggregate.aggregate_s1`, `harness.report.EvalReport`)."""

from __future__ import annotations

from twin.harness.schema import S1Item


def build_item_bank(*, held_out_fragment_ids: list[str], teacher: object) -> list[S1Item]:
    raise NotImplementedError(
        "EVAL.md §3.2: the S1 item bank is generated by a real Teacher call "
        "against real held-out fragments (twin/PLAN.md Phase 2) — not yet run."
    )
