"""L0: pure data model. Imports nothing else from this package."""

from videogen.core.enums import (
    AudioLayer,
    CaptionKind,
    FormatStrategy,
    GenMode,
    JobState,
    SceneMode,
    Severity,
    SourceKind,
    TransitionKind,
    TransitionReason,
)
from videogen.core.errors import (
    ConfigError,
    CostCeilingExceeded,
    FormatPolicyViolation,
    GateFailure,
    GraphValidationError,
    InsufficientHostRamError,
    PodError,
    ProviderError,
    ProviderJobFailed,
    ProviderSubmitError,
    ProviderTimeout,
    UnknownKeyError,
    UnknownProviderError,
    VideogenError,
)
from videogen.core.models import (
    CaptionCue,
    FormatPlan,
    GateFinding,
    GateReport,
    RenderResult,
    Scene,
    Segment,
    Shot,
    VideoSpec,
)
from videogen.core.provider_spec import ClipAsset, ClipJob, ClipRequest, ProviderCapabilities

__all__ = [
    "AudioLayer",
    "CaptionCue",
    "CaptionKind",
    "ClipAsset",
    "ClipJob",
    "ClipRequest",
    "ConfigError",
    "CostCeilingExceeded",
    "FormatPlan",
    "FormatPolicyViolation",
    "FormatStrategy",
    "GateFailure",
    "GateFinding",
    "GateReport",
    "GenMode",
    "GraphValidationError",
    "InsufficientHostRamError",
    "JobState",
    "PodError",
    "ProviderCapabilities",
    "ProviderError",
    "ProviderJobFailed",
    "ProviderSubmitError",
    "ProviderTimeout",
    "RenderResult",
    "Scene",
    "SceneMode",
    "Segment",
    "Severity",
    "Shot",
    "SourceKind",
    "TransitionKind",
    "TransitionReason",
    "UnknownKeyError",
    "UnknownProviderError",
    "VideoSpec",
    "VideogenError",
]
